name: My First CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:              # ← ADD THIS
    branches: [ main ]       # ← ADD THIS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout my code
        uses: actions/checkout@v3

      - name: Step 2 - Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Step 3 - Run my Python file
        run: python calculator.py